### ISSUE TITLE
2 x Deprecated Warnings

### ISSUE THREAD

**Issue by SchumacherFM** [magento-hackathon/composer-command-integrator#10]
PHP Deprecated:  "Symfony\Component\Console\Helper\DialogHelper" is deprecated since version 2.5 and will be removed in 3.0. Use "Symfony\Component\Console\Helper\QuestionHelper" instead

PHP Deprecated:  The Symfony\Component\Console\Helper\ProgressHelper class is deprecated since version 2.5 and will be removed in 3.0. Use the Symfony\Component\Console\Helper\ProgressBar class instead.

Can I send you a PR to fix this? That PR would check for both class and if the new class does not exists then falls back to the old class names.

Those warning are annoying and do not cause any harms.

**Comment by Flyingmana** [comment]
if it works for old versions too, sure :)
